In [1]:
import numpy as np

In [2]:
l=[12,21,34]

In [10]:
nparray=np.array(l)

In [11]:
nparray

array([12, 21, 34])

In [12]:
nparray.mean()

22.333333333333332

In [13]:
nparray.dtype

dtype('int32')

In [14]:
nparray

array([12, 21, 34])

# slice array

```Slicing in array is different from  list. In array we create a view of array while slicing but with list we create a copy so any change in copy will not effect the mail list but with array if we make any changes with view it will change the main array```

In [15]:
nparray[2:]

array([34])

In [16]:
b=nparray[2:]

In [17]:
b

array([34])

In [19]:
nparray

array([12, 21, 34])

In [20]:
b[0]=12

In [21]:
b

array([12])

In [22]:
nparray

array([12, 21, 12])

```alternative is to use copy funtion of array which not change the main array```

In [23]:
c=np.copy(nparray[2:])

In [24]:
c

array([12])

In [26]:
nparray

array([12, 21, 12])

In [27]:
c[0]=24

In [28]:
c

array([24])

In [29]:
nparray

array([12, 21, 12])